### ISSUE TITLE
Pricing page useless on mobile

### ISSUE THREAD

**Issue by tim-gromeyer** [nuttyartist/daino-notes-public#2]
Just take a look at the screenshot

![Screenshot_20241021_153719_Kiwi Browser](https://github.com/user-attachments/assets/61d26a1b-1b7b-4ad2-9305-d29f59264235)

The red thing looks like the effect used for the "40% discount for students" button

**Comment by nuttyartist** [comment]
What device you're using? Can't reproduce this on my phone (although there are other improvements I should make for this page on mobile).

**Comment by tim-gromeyer** [comment]
Samsung Galaxy S21FE
Android 14
Kiwi Browser 124.0.6327.4

**Comment by nuttyartist** [comment]
Thanks! I'll let you know when I create a fix to test.

**Comment by nuttyartist** [comment]
Can you test if this is fixed? I simply deleted it since it's not really needed.

**Comment by tim-gromeyer** [comment]
Yes, much better now
